const assert=require('assert/strict'),fs=require('fs');
const {setup}=require('./support.cjs');
(async()=>{
 const e=await setup();
 try{
  fs.mkdirSync('output',{recursive:true});
  const board=await e.page();await board.evaluate(()=>{__qa.start();__qa.mode('light');__qa.selectClass('5-A');});
  const phone=await e.page();await phone.setViewportSize({width:393,height:660});
  let drop=false;
  await phone.exposeFunction('__send',data=>board.evaluate(data=>window.__receive(data),data));
  await board.exposeFunction('__send',data=>{if(drop&&data.type==='ACTION_ACK'){drop=false;return;}return phone.evaluate(data=>window.__receive(data),data);});
  const connect=async()=>{
   await phone.evaluate(()=>{document.getElementById('startup-overlay').classList.add('hidden');document.querySelector('.app-shell').style.display='none';document.getElementById('mobile-controller').classList.remove('hidden');__qa.connect('controller');});
   await board.evaluate(()=>__qa.connect('host'));await phone.waitForFunction(()=>__qa.state().remoteStudentClass==='5-A');
  };
  await connect();
  const state=()=>board.evaluate(()=>__qa.state());
  const assign=async(team,id)=>{await phone.locator('#mobile-agent-'+team).click();await phone.locator(`[data-agent-student="${id}"]`).click();await phone.waitForFunction(()=>__qa.state().remotePending===0);};
  await board.locator('[data-team="slytherin"][data-type="secretAgent"]').click();
  await phone.waitForSelector('#agent-picker[open]');
  assert.equal(await phone.locator('.agent-name-choice').count(),19);
  assert.equal(await phone.locator('[data-agent-student^="5-A:slytherin"]').count(),0);
  assert.equal(await board.locator('#agent-picker[open]').count(),0);
  await phone.screenshot({path:'output/secret-agent-picker.png'});
  await phone.locator('[data-agent-student="5-A:gryffindor:0"]').click();
  await phone.waitForFunction(()=>__qa.state().remotePending===0);
  assert.equal((await state()).secretAgents.assignments.slytherin.studentId,'5-A:gryffindor:0');
  assert.equal(await board.locator('.powerup-btn[data-team="slytherin"][data-type="secretAgent"]').getAttribute('aria-pressed'),'true');
  assert.doesNotMatch(await board.locator('#ticker-text').textContent(),/Emobi Nese/);
  assert.equal(await board.evaluate(()=>__qa.selectClass('5-C').ok),false);
  // Duplicate agents are unavailable, including for a different receiving team.
  await phone.locator('#mobile-agent-hufflepuff').click();
  await phone.waitForFunction(()=>document.getElementById('agent-picker').open&&document.getElementById('agent-picker-title').textContent.startsWith('Hufflepuff'));
  assert.ok(await phone.locator('[data-agent-student="5-A:gryffindor:0"]').isDisabled());
  await phone.getByRole('button',{name:'Close Secret Agent',exact:true}).click();await phone.waitForFunction(()=>__qa.state().remotePending===0);
  // Full actual points include double points; a subsequent reset keeps the liability.
  await board.locator('[data-team="gryffindor"][data-type="doubleUp"]').click();
  await board.evaluate(()=>__qa.studentAward('gryffindor','5-A:gryffindor:0'));
  let earned=(await state()).studentContributions['5-A:gryffindor:0'].points;assert.equal(earned,20);
  await board.evaluate(()=>__qa.resetTeam('gryffindor'));
  await board.locator('[data-team="gryffindor"][data-type="shield"]').click();
  const before=await state();assert.equal(before.pointsByTeam.gryffindor,0);
  await phone.locator('#mobile-agent-slytherin').click();drop=true;await phone.locator('#agent-reveal-now').click();
  await phone.waitForSelector('#agent-remote-reveal:not([hidden])');
  await phone.waitForFunction(()=>__qa.state().remotePending===0);
  let after=await state();assert.deepEqual(after.pointsByTeam,{gryffindor:-earned,slytherin:earned,hufflepuff:0,ravenclaw:0});assert.deepEqual(after.levelsByTeam,before.levelsByTeam);
  assert.deepEqual(after.studentContributions,before.studentContributions);assert.deepEqual(after.mission,before.mission);
  assert.equal(after.secretAgents.assignments.slytherin.status,'revealed');
  assert.match(await board.locator('#agent-reveal-cards').textContent(),/Emobi Nese.*Gryffindor.*Slytherin.*20 points transferred/s);
  await board.screenshot({path:'output/secret-agent-reveal.png'});
  // Reload while reveal is open; transfer must never repeat.
  await board.evaluate(()=>__qa.checkpoint());await board.reload();await board.waitForFunction(()=>Boolean(window.__qa)&&LeagueAccess.granted);await board.evaluate(()=>__qa.start({resume:true}));await board.evaluate(()=>__qa.connect('host'));
  await board.waitForSelector('#agent-reveal-overlay.visible');assert.deepEqual((await state()).pointsByTeam,{gryffindor:-earned,slytherin:earned,hufflepuff:0,ravenclaw:0});
  await phone.locator('#agent-remote-continue').click();await phone.waitForFunction(()=>__qa.state().remotePending===0);
  assert.equal((await state()).scene,null);
  await board.locator('#undo-btn').click();
  assert.equal((await state()).secretAgents.assignments.slytherin.status,'active');
  assert.deepEqual((await state()).pointsByTeam,{gryffindor:0,slytherin:0,hufflepuff:0,ravenclaw:0});
  await phone.locator('#mobile-agent-slytherin').click();await phone.locator('#agent-reveal-now').click();
  await phone.waitForSelector('#agent-remote-reveal:not([hidden])');
  assert.deepEqual((await state()).pointsByTeam,{gryffindor:-earned,slytherin:earned,hufflepuff:0,ravenclaw:0});
  await phone.locator('#agent-remote-continue').click();await phone.waitForFunction(()=>__qa.state().remotePending===0);
  await board.evaluate(()=>__qa.studentAward('gryffindor','5-A:gryffindor:0'));
  after=await state();assert.equal(after.pointsByTeam.slytherin,earned);assert.ok(after.pointsByTeam.gryffindor>-earned);
  console.log('PASS private roster selection, no duplicate target, class lock, bonus totals, late shield does not undo earlier agent selection, full negative transfer after reset, unchanged levels/participation, lost receipt and reveal recovery');
  // New session and two assignments. Finishing must reveal both before the summary/arena.
  await board.evaluate(()=>{__qa.reset({clearUndo:true});__qa.selectClass('5-A');});await phone.waitForFunction(()=>__qa.state().remoteStudentClass==='5-A');
  await assign('slytherin','5-A:gryffindor:0');await assign('hufflepuff','5-A:gryffindor:1');
  await board.evaluate(()=>{__qa.creditCustom('gryffindor','5-A:gryffindor:0',1250);__qa.creditCustom('gryffindor','5-A:gryffindor:1',750);__qa.resetTeam('gryffindor');});
  const counts=(await state()).studentContributions;
  await phone.locator('#mobile-finish-btn').click();await phone.locator('#mobile-finish-confirm-btn').click();
  await board.waitForSelector('#agent-reveal-overlay.visible');
  assert.deepEqual((await state()).pointsByTeam,{gryffindor:-2000,slytherin:1250,hufflepuff:750,ravenclaw:0});
  assert.equal(await board.locator('.agent-reveal-card').count(),2);
  assert.equal((await state()).secretAgents.reveal.finish,true);
  assert.equal((await phone.evaluate(()=>__qa.state())).remoteRecords.cachedLeaderboardRecord,null);
  await board.evaluate(()=>__qa.checkpoint());await board.reload();await board.waitForFunction(()=>Boolean(window.__qa)&&LeagueAccess.granted);
  await board.evaluate(()=>__qa.start({resume:true}));await board.evaluate(()=>__qa.connect('host'));
  await board.waitForSelector('#agent-reveal-overlay.visible');assert.deepEqual((await state()).pointsByTeam,{gryffindor:-2000,slytherin:1250,hufflepuff:750,ravenclaw:0});
  await phone.locator('#agent-remote-continue').click();
  await board.waitForFunction(()=>__qa.state().scene==='arena');
  await phone.waitForFunction(()=>Boolean(__qa.state().remoteRecords.cachedLeaderboardRecord));
  const finalRecord=await phone.evaluate(()=>__qa.state().remoteRecords.cachedLeaderboardRecord);
  assert.equal(finalRecord.standings[0].name,'Slytherin');
  assert.equal(finalRecord.standings[0].points,1250);
  assert.equal(finalRecord.standings.at(-1).points,-2000);
  assert.deepEqual((await state()).studentContributions,counts);
  console.log('PASS multiple agents transfer together before final standings; negative score included in final record; counts unchanged');
  await board.evaluate(()=>{__qa.reset({clearUndo:true});__qa.selectClass('5-A');});
  await phone.waitForFunction(()=>!document.querySelector('.mobile-agent-button.active,.mobile-agent-button.used'));
  await assign('slytherin','5-A:gryffindor:0');await assign('gryffindor','5-A:slytherin:0');
  await assign('hufflepuff','5-A:ravenclaw:0');await assign('ravenclaw','5-A:hufflepuff:0');
  await board.evaluate(()=>{for(const t of LeagueStudents.teams){__qa.creditCustom(t,LeagueStudents.members('5-A',t)[0].id,10);__qa.resetTeam(t);}});
  await board.locator('#finish-btn').click();await board.waitForSelector('#agent-reveal-overlay.visible');
  assert.equal(await board.locator('.agent-reveal-card').count(),4);
  assert.deepEqual((await state()).pointsByTeam,{gryffindor:0,slytherin:0,hufflepuff:0,ravenclaw:0});
  assert.ok(await board.locator('#agent-continue').evaluate(b=>b.getBoundingClientRect().bottom<=innerHeight));
  await board.screenshot({path:'output/secret-agent-four-reveals.png'});
  await board.locator('#agent-continue').click();await board.waitForFunction(()=>__qa.state().scene==='arena');
  console.log('PASS four simultaneous reciprocal agents fit the board; zero net balances still finish; pending final reveal survives reload');
  assert.deepEqual(e.errors,[]);
 }finally{await e.close();}
})().catch(err=>{console.error(err);process.exit(1);});
