const assert=require('node:assert/strict');
(async()=>{const {handleTurn}=await import('../netlify/functions/turn-credentials.mjs'),A=await require('./fixture.cjs').auth();
// v12.0.0: a signed-in device (teacher session) is needed; the provider is called through global fetch as on the site.
const handler=request=>handleTurn(A.signed(request.url,{}),{store:A.store,secret:A.secret,fetcher:(...a)=>global.fetch(...a)});const original=global.fetch,originalError=console.error,oldId=process.env.CLOUDFLARE_TURN_KEY_ID,oldToken=process.env.CLOUDFLARE_TURN_KEY_API_TOKEN;
try{console.error=()=>{};process.env.CLOUDFLARE_TURN_KEY_ID='test-key';process.env.CLOUDFLARE_TURN_KEY_API_TOKEN='test-token';for(const status of [401,403,404,429,500]){global.fetch=async()=>new Response('Provider error',{status});const result=await handler(new Request('https://school.test/api/turn-credentials'));const body=await result.json();assert.equal(result.status,502);assert.equal(body.providerStatus,status);assert(body.setup);assert(!JSON.stringify(body).includes('test-token'));}
global.fetch=async()=>new Response(JSON.stringify({iceServers:[{urls:['turn:test.invalid:3478'],username:'temporary',credential:'temporary'}]}));const result=await handler(new Request('https://school.test/api/turn-credentials'));assert.equal(result.status,200);assert.equal((await result.json()).iceServers.length,1);
delete process.env.CLOUDFLARE_TURN_KEY_API_TOKEN;assert.equal((await handler(new Request('https://school.test/api/turn-credentials'))).status,503);
assert.equal((await handleTurn(new Request('https://school.test/api/turn-credentials'),{store:A.store,secret:A.secret})).status,401,'no session, no credentials');
console.log('PASS TURN needs a signed-in device; missing configuration, provider-status diagnostics, successful credentials, and no long-lived token in responses.');
}finally{global.fetch=original;console.error=originalError;if(oldId===undefined)delete process.env.CLOUDFLARE_TURN_KEY_ID;else process.env.CLOUDFLARE_TURN_KEY_ID=oldId;if(oldToken===undefined)delete process.env.CLOUDFLARE_TURN_KEY_API_TOKEN;else process.env.CLOUDFLARE_TURN_KEY_API_TOKEN=oldToken;}})().catch(e=>{console.error(e);process.exitCode=1;});
